env:
  browser: true
  es2021: true
  jest/globals: true
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2016
  sourceType: module
  project: tsconfig.json
plugins:
  - react
  - '@typescript-eslint'
  - jest
  - prefer-arrow
  - import
  - jsx-a11y
extends:
  - eslint:recommended
  - plugin:import/recommended
  - plugin:import/typescript
  - airbnb
  - airbnb-typescript
  - airbnb/hooks
  - plugin:react/recommended
  - plugin:jest/recommended
  - plugin:jest/style
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/recommended-requiring-type-checking
  - plugin:tailwind/recommended
  - plugin:jsx-a11y/recommended
  - plugin:@next/next/recommended
  - prettier
rules:
  prefer-arrow/prefer-arrow-functions:
    - error
    - disallowPrototype: true
      singleReturnOnly: false
      classPropertiesAllowed: false
  react/react-in-jsx-scope: off
  react/jsx-curly-brace-presence: off
  react/require-default-props: off
  react/jsx-handler-names:
    - error
    - checkLocalVariables: false
      checkInlineFunction: true
  react/function-component-definition:
    - error
    - namedComponents: arrow-function
  import/prefer-default-export: off
ignorePatterns:
  - node_modules
  - dist
  - coverage
settings:
  react:
    version: detect
  jest:
    version: detect
