import { irrelevantRouteWarningStarts } from '../../src/services/getJourney';
import { mockWarning } from '../../src/services/mockWarnings';

const mockGoogleResponseTransit: google.maps.DirectionsResult = {
  geocoded_waypoints: [
    {
      geocoder_status: 'OK',
      place_id: 'ChIJ-Q0Y1GcEdkgRpwW1k3QNek0',
      types: [
        'establishment',
        'point_of_interest',
        'subway_station',
        'transit_station',
      ],
    },
    {
      geocoder_status: 'OK',
      place_id: 'ChIJEbKYCJIadkgRszYnYCnjOAs',
      types: ['premise'],
    },
  ],
  routes: [
    {
      bounds: {
        Bb: {
          g: 51.4626,
          h: 51.546510000000005,
        },
        Ra: {
          g: -0.17602,
          h: -0.11475,
        },
      },
      copyrights: 'Map data ©2021',
      legs: [
        {
          arrival_time: {
            text: '11:30pm',
            time_zone: 'Europe/London',
            value: new Date('2021-12-06T23:30:19.000Z'),
          },
          departure_time: {
            text: '11:00pm',
            time_zone: 'Europe/London',
            value: new Date('2021-12-06T23:00:00.000Z'),
          },
          distance: {
            text: '12.7 km',
            value: 12742,
          },
          duration: {
            text: '30 mins',
            value: 1819,
          },
          end_address: '27 Lancaster Grove, Belsize Park, London NW3 4EX, UK',
          end_location: {},
          start_address: 'Brixton, Brixton Rd, London SW9 8HE, UK',
          start_location: {},
          steps: [
            {
              distance: {
                text: '6.3 km',
                value: 6300,
              },
              duration: {
                text: '9 mins',
                value: 540,
              },
              end_location: {},
              polyline: {
                points:
                  'ghbyHdlU}B`[{@|Hg@fCo@nBqAzCeClD_BfB_BbAmBj@uC\\C?iEUcDw@yCkA_FeC}EgD{@_A?AsCcDy@aA]a@]_@UYGE]]uAqAg@_@o@c@kBi@O?c@C}@EiBF{ATYFeARiB\\qDp@a@HmCf@uEz@a@HuEz@eARc@HiB\\a@Pa@PcAb@KBSR_@ZEBWZYZ[l@Wd@s@tAq@pAA@Uh@Wj@o@tAi@nACFWj@Sd@Wr@Ul@Ul@k@zASl@k@|Ak@zAi@zAUl@Ul@k@zA_@fAIRk@|AM^ELi@hB_@dCKjAIv@Gv@CXC\\Cx@MbDUbFWnDGv@oApNmAjH}ArFoDfF}C|BIBqClAiFZ_CG_AC_ACe@CgSw@eAEwNk@cCI_EKoCIgGEeDJE??@',
              },
              start_location: {},
              travel_mode: 'TRANSIT',
              encoded_lat_lngs:
                'ghbyHdlU}B`[{@|Hg@fCo@nBqAzCeClD_BfB_BbAmBj@uC\\C?iEUcDw@yCkA_FeC}EgD{@_A?AsCcDy@aA]a@]_@UYGE]]uAqAg@_@o@c@kBi@O?c@C}@EiBF{ATYFeARiB\\qDp@a@HmCf@uEz@a@HuEz@eARc@HiB\\a@Pa@PcAb@KBSR_@ZEBWZYZ[l@Wd@s@tAq@pAA@Uh@Wj@o@tAi@nACFWj@Sd@Wr@Ul@Ul@k@zASl@k@|Ak@zAi@zAUl@Ul@k@zA_@fAIRk@|AM^ELi@hB_@dCKjAIv@Gv@CXC\\Cx@MbDUbFWnDGv@oApNmAjH}ArFoDfF}C|BIBqClAiFZ_CG_AC_ACe@CgSw@eAEwNk@cCI_EKoCIgGEeDJE??@',
              path: [
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
              ],
              lat_lngs: [
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
              ],
              instructions: 'Subway towards Seven Sisters',
              maneuver: '',
              start_point: {},
              end_point: {},
              transit: {
                arrival_stop: {
                  location: {},
                  name: 'Green Park',
                },
                arrival_time: {
                  text: '11:09pm',
                  time_zone: 'Europe/London',
                  value: new Date('2021-12-06T23:09:00.000Z'),
                },
                departure_stop: {
                  location: {},
                  name: 'Brixton',
                },
                departure_time: {
                  text: '11:00pm',
                  time_zone: 'Europe/London',
                  value: new Date('2021-12-06T23:00:00.000Z'),
                },
                headsign: 'Seven Sisters',
                line: {
                  agencies: [
                    {
                      name: 'Transport for London',
                      url: 'http://tfl.gov.uk/',
                    },
                  ],
                  color: '#00a3e0',
                  name: 'Victoria line',
                  short_name: 'Victoria',
                  text_color: '#ffffff',
                  vehicle: {
                    icon: 'https://maps.gstatic.com/mapfiles/transit/iw2/6/subway2.png',
                    local_icon:
                      'https://maps.gstatic.com/mapfiles/transit/iw2/6/uk-london-underground.png',
                    name: 'Subway',
                    type: 'SUBWAY',
                  },
                },
                num_stops: 5,
              },
            },
            {
              distance: {
                text: '66 m',
                value: 66,
              },
              duration: {
                text: '1 min',
                value: 67,
              },
              end_location: {},
              polyline: {
                points: 'yyjyHv{ZZ{D',
              },
              start_location: {},
              steps: [
                {
                  distance: {
                    text: '66 m',
                    value: 66,
                  },
                  duration: {
                    text: '1 min',
                    value: 67,
                  },
                  end_location: {},
                  polyline: {
                    points: 'yyjyHv{ZZ{D',
                  },
                  start_location: {},
                  travel_mode: 'WALKING',
                  encoded_lat_lngs: 'yyjyHv{ZZ{D',
                  path: [{}, {}],
                  lat_lngs: [{}, {}],
                  maneuver: '',
                },
              ],
              travel_mode: 'WALKING',
              encoded_lat_lngs: 'yyjyHv{ZZ{D',
              path: [{}, {}],
              lat_lngs: [{}, {}],
              instructions: 'Walk to Green Park',
              maneuver: '',
              start_point: {},
              end_point: {},
            },
            {
              distance: {
                text: '5.8 km',
                value: 5795,
              },
              duration: {
                text: '8 mins',
                value: 486,
              },
              end_location: {},
              polyline: {
                points:
                  '}xjyHzuZsBF@jBJnNA|AQvDeAxEq@`BmArB}ApAoMbEyO~BaEf@?BeBPeABgAAmAK_AM_AQu@OmA_@cA_@qAo@{BsAcCcBwB}Ay@i@iCcBkAu@gAs@WMUESC_@AS?UD]FYHOHMJQNOTMVMVKRIRKXGXIZGZC^Ad@FnARnFBf@@dALnEB`@B`@l@|Fj@lFBj@?h@Aj@Cf@Cd@E\\EZGVGTGNIPGNKNMPSVo@l@A@@DCBQPWXUXONEJEJGLKV[p@gFzL}Np]GNg@nAa@dACFa@`AS`@KT_@p@KRYj@Wb@CBk@|@uAfBa@f@g@n@A@qBlCmCnDmCnDoCnDmCpDiDrEqAbBsAfBEDYXYNc@NaBb@YFYD]B_@DkBJUBuAQeJ}@yFk@uEc@uBSo@EeAC{@D?m@',
              },
              start_location: {},
              travel_mode: 'TRANSIT',
              encoded_lat_lngs:
                '}xjyHzuZsBF@jBJnNA|AQvDeAxEq@`BmArB}ApAoMbEyO~BaEf@?BeBPeABgAAmAK_AM_AQu@OmA_@cA_@qAo@{BsAcCcBwB}Ay@i@iCcBkAu@gAs@WMUESC_@AS?UD]FYHOHMJQNOTMVMVKRIRKXGXIZGZC^Ad@FnARnFBf@@dALnEB`@B`@l@|Fj@lFBj@?h@Aj@Cf@Cd@E\\EZGVGTGNIPGNKNMPSVo@l@A@@DCBQPWXUXONEJEJGLKV[p@gFzL}Np]GNg@nAa@dACFa@`AS`@KT_@p@KRYj@Wb@CBk@|@uAfBa@f@g@n@A@qBlCmCnDmCnDoCnDmCpDiDrEqAbBsAfBEDYXYNc@NaBb@YFYD]B_@DkBJUBuAQeJ}@yFk@uEc@uBSo@EeAC{@D?m@',
              path: [
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
              ],
              lat_lngs: [
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
              ],
              instructions: 'Subway towards Stanmore',
              maneuver: '',
              start_point: {},
              end_point: {},
              transit: {
                arrival_stop: {
                  location: {},
                  name: 'Swiss Cottage Station',
                },
                arrival_time: {
                  text: '11:23pm',
                  time_zone: 'Europe/London',
                  value: new Date('2021-12-06T23:23:06.000Z'),
                },
                departure_stop: {
                  location: {},
                  name: 'Green Park',
                },
                departure_time: {
                  text: '11:15pm',
                  time_zone: 'Europe/London',
                  value: new Date('2021-12-06T23:15:00.000Z'),
                },
                headsign: 'Stanmore',
                line: {
                  agencies: [
                    {
                      name: 'Transport for London',
                      url: 'http://tfl.gov.uk/',
                    },
                  ],
                  color: '#7c878e',
                  name: 'Jubilee line',
                  short_name: 'Jubilee',
                  text_color: '#ffffff',
                  vehicle: {
                    icon: 'https://maps.gstatic.com/mapfiles/transit/iw2/6/subway2.png',
                    local_icon:
                      'https://maps.gstatic.com/mapfiles/transit/iw2/6/uk-london-underground.png',
                    name: 'Subway',
                    type: 'SUBWAY',
                  },
                },
                num_stops: 4,
              },
            },
            {
              distance: {
                text: '0.6 km',
                value: 581,
              },
              duration: {
                text: '7 mins',
                value: 433,
              },
              end_location: {},
              polyline: {
                points:
                  '_aryH|ca@{@g@CB?AOe@EQMe@K@EAAAACAAGc@Ki@IWI?CACAEGGIGMGOGOSa@e@cAaA{BUi@AAe@gAO]OWwAT[Fo@JE@C@G?C?AAMGBIr@uE',
              },
              start_location: {},
              steps: [
                {
                  distance: {
                    text: '35 m',
                    value: 35,
                  },
                  duration: {
                    text: '1 min',
                    value: 36,
                  },
                  end_location: {},
                  polyline: {
                    points: '_aryH|ca@{@g@',
                  },
                  start_location: {},
                  travel_mode: 'WALKING',
                  encoded_lat_lngs: '_aryH|ca@{@g@',
                  path: [{}, {}],
                  lat_lngs: [{}, {}],
                  instructions: 'Take exit <span class="location"></span>',
                  maneuver: '',
                },
                {
                  distance: {
                    text: '0.1 km',
                    value: 98,
                  },
                  duration: {
                    text: '1 min',
                    value: 67,
                  },
                  end_location: {},
                  polyline: {
                    points: '_cryHxba@?AOe@EQMe@K@EAAAACAAGc@Ki@IWI?',
                  },
                  start_location: {},
                  travel_mode: 'WALKING',
                  encoded_lat_lngs: '_cryHxba@?AOe@EQMe@K@EAAAACAAGc@Ki@IWI?',
                  path: [
                    {},
                    {},
                    {},
                    {},
                    {},
                    {},
                    {},
                    {},
                    {},
                    {},
                    {},
                    {},
                    {},
                    {},
                  ],
                  lat_lngs: [
                    {},
                    {},
                    {},
                    {},
                    {},
                    {},
                    {},
                    {},
                    {},
                    {},
                    {},
                    {},
                    {},
                    {},
                  ],
                  instructions: 'Head <b>northeast</b> toward <b>Eton Ave</b>',
                  maneuver: '',
                },
                {
                  distance: {
                    text: '0.2 km',
                    value: 218,
                  },
                  duration: {
                    text: '3 mins',
                    value: 162,
                  },
                  end_location: {},
                  maneuver: 'turn-slight-left',
                  polyline: {
                    points: 'cfryHj|`@CACAEGGIGMGOGOSa@e@cAaA{BUi@AAe@gAO]OW',
                  },
                  start_location: {},
                  travel_mode: 'WALKING',
                  encoded_lat_lngs:
                    'cfryHj|`@CACAEGGIGMGOGOSa@e@cAaA{BUi@AAe@gAO]OW',
                  path: [
                    {},
                    {},
                    {},
                    {},
                    {},
                    {},
                    {},
                    {},
                    {},
                    {},
                    {},
                    {},
                    {},
                    {},
                    {},
                    {},
                  ],
                  lat_lngs: [
                    {},
                    {},
                    {},
                    {},
                    {},
                    {},
                    {},
                    {},
                    {},
                    {},
                    {},
                    {},
                    {},
                    {},
                    {},
                    {},
                  ],
                  instructions: 'Slight <b>left</b> onto <b>Adamson Rd</b>',
                },
                {
                  distance: {
                    text: '0.1 km',
                    value: 111,
                  },
                  duration: {
                    text: '1 min',
                    value: 84,
                  },
                  end_location: {},
                  maneuver: 'turn-left',
                  polyline: {
                    points: 'knryHzm`@wAT[Fo@JE@C@G?C?AAMGBI',
                  },
                  start_location: {},
                  travel_mode: 'WALKING',
                  encoded_lat_lngs: 'knryHzm`@wAT[Fo@JE@C@G?C?AAMGBI',
                  path: [{}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}],
                  lat_lngs: [{}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}],
                  instructions: 'Turn <b>left</b> onto <b>Crossfield Rd</b>',
                },
                {
                  distance: {
                    text: '0.1 km',
                    value: 119,
                  },
                  duration: {
                    text: '1 min',
                    value: 84,
                  },
                  end_location: {},
                  maneuver: 'turn-right',
                  polyline: {
                    points: 'qtryHtn`@r@uE',
                  },
                  start_location: {},
                  travel_mode: 'WALKING',
                  encoded_lat_lngs: 'qtryHtn`@r@uE',
                  path: [{}, {}],
                  lat_lngs: [{}, {}],
                  instructions:
                    'Turn <b>right</b> onto <b>Lancaster Grove</b><div style="font-size:0.9em">Destination will be on the left</div>',
                },
              ],
              travel_mode: 'WALKING',
              encoded_lat_lngs:
                '_aryH|ca@{@g@CB?AOe@EQMe@K@EAAAACAAGc@Ki@IWI?CACAEGGIGMGOGOSa@e@cAaA{BUi@AAe@gAO]OWwAT[Fo@JE@C@G?C?AAMGBIr@uE',
              path: [
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
              ],
              lat_lngs: [
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
              ],
              instructions:
                'Walk to 27 Lancaster Grove, Belsize Park, London NW3 4EX, UK',
              maneuver: '',
              start_point: {},
              end_point: {},
            },
          ],
          traffic_speed_entry: [],
          via_waypoint: [],
          via_waypoints: [],
        },
      ],
      overview_polyline:
        'ghbyHdlU}B`[{@|Hg@fCo@nBqAzCeClD_BfB_BbAmBj@yC\\iEUcDw@yCkA_FeC}EgD{@_AsCeDkC}Ce@c@uAqAg@_@o@c@kBi@s@C}@EiBFuB\\cKlBoXdFsCjAqAnAYZ[l@kAzBaBhDuBxEwAtDyGvQcBxEo@vB_@dCKjAQnBGv@Q|EUbFWnDGv@oApNmAjH}ArFoDfFgD`CqClAiFZ_EKsXeA{Ru@oIUgGEkDJZyDsBF@jBJnNA|AQvDeAxEq@`BmArB}ApAoMbEyO~BaEf@eBTmC@mCYuBa@qC_AqAo@{BsA{FaEwIwFm@Ss@Ei@Dw@P]Ta@d@q@vASr@Qv@EdAZ~HV~Ip@~Gj@lFBj@AtAGlAKx@Ol@e@`Aa@h@q@n@AHi@j@e@h@KVwGrOeO`^iAtCe@hA_@v@}AtCo@`AwBnCiHnJuQdVeDjE_@^}@^{Bj@w@HkCPUBuAQ_RiBkIw@uBI{@D?m@{@g@CBOg@Sw@Q?AAWsAIWI?GC]o@qEcKOWwATkARUBOIv@_F',
      summary: '',
      warnings: [...irrelevantRouteWarningStarts, mockWarning],
      waypoint_order: [],
      overview_path: [
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
      ],
    },
  ],
} as unknown as google.maps.DirectionsResult;

export default mockGoogleResponseTransit;
